-- Run this file in Supabase SQL Editor after creating the project.
-- Supabase Auth stores password hashes securely in auth.users.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name text not null check (char_length(trim(name)) between 1 and 60),
  user_id uuid not null references auth.users(id) on delete cascade
);

create table if not exists public.tasks (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(trim(title)) between 1 and 120),
  description text check (char_length(description) <= 500),
  due_date date,
  completed boolean not null default false,
  category_id bigint references public.categories(id) on delete set null,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.categories enable row level security;
alter table public.tasks enable row level security;

-- Data API table access is explicit. RLS policies below still decide which
-- rows each authenticated user may read or modify.
revoke all on table public.categories from anon;
revoke all on table public.tasks from anon;
revoke all on sequence public.categories_id_seq from anon;
revoke all on sequence public.tasks_id_seq from anon;
revoke all on table public.categories from authenticated;
revoke all on table public.tasks from authenticated;
revoke all on sequence public.categories_id_seq from authenticated;
revoke all on sequence public.tasks_id_seq from authenticated;
grant select, insert, update, delete on table public.categories to authenticated;
grant select, insert, update, delete on table public.tasks to authenticated;
grant usage, select on sequence public.categories_id_seq to authenticated;
grant usage, select on sequence public.tasks_id_seq to authenticated;

create policy "Users can view their own categories"
  on public.categories for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own categories"
  on public.categories for insert
  to authenticated
  with check ((select auth.uid()) = user_id);

create policy "Users can update their own categories"
  on public.categories for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

create policy "Users can delete their own categories"
  on public.categories for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can view their own tasks"
  on public.tasks for select
  to authenticated
  using ((select auth.uid()) = user_id);

create policy "Users can create their own tasks"
  on public.tasks for insert
  to authenticated
  with check (
    (select auth.uid()) = user_id
    and (
      category_id is null
      or exists (
        select 1 from public.categories
        where categories.id = category_id
          and categories.user_id = (select auth.uid())
      )
    )
  );

create policy "Users can update their own tasks"
  on public.tasks for update
  to authenticated
  using ((select auth.uid()) = user_id)
  with check (
    (select auth.uid()) = user_id
    and (
      category_id is null
      or exists (
        select 1 from public.categories
        where categories.id = category_id
          and categories.user_id = (select auth.uid())
      )
    )
  );

create policy "Users can delete their own tasks"
  on public.tasks for delete
  to authenticated
  using ((select auth.uid()) = user_id);

create index if not exists categories_user_id_idx on public.categories(user_id);
create index if not exists tasks_user_id_idx on public.tasks(user_id);
create index if not exists tasks_category_id_idx on public.tasks(category_id);
